version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development       # or production
      HOST: 0.0.0.0
      PORT: "4000"
      # >>> REQUIRED ENV (from your repo README) <<<
      MONGO_URL: "mongodb://admin:password@mongo:27017/fooddb?authSource=admin"
      JWT_SECRET: "devsecret"
      SALT: "10"
      STRIPE_SECRET_KEY: "sk_test_xxx"
    depends_on:
      - mongo

volumes:
  mongo_data:
